name: Release Pipeline

on:
  push:
    branch:
      - main
jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run test script
        run: echo "Runner is working test2"
